Repository HireUp-Turing/HireUp_frontend, pull requests merged in 2020-11, with the labels that each got.

#53 Feature/ge inbox
  src/assets/api-calls.tsx
  src/assets/definitions.tsx
  src/assets/user-maker.tsx
  src/components/App/App.scss
  src/components/App/App.tsx
  src/components/Applicant/Applicant.tsx
  src/components/ApplicantForm/ApplicantForm.tsx
  src/components/Header/Header.scss
  src/components/Header/Header.tsx
  src/components/Home/Home.scss
  src/components/Home/Home.tsx
  src/components/Inbox/Inbox.scss
  src/components/Inbox/Inbox.tsx
  src/components/SearchResults/SearchResults.scss
  src/components/SearchResults/SearchResults.tsx
  src/contexts/index.tsx
  src/index.scss
  src/routes/applicant.tsx
Labels: FE

#55 Feature/employer messages
  public/chat-gray.svg
  public/chat-pink.svg
  src/assets/api-calls.tsx
  src/assets/definitions.tsx
  src/components/App/App.tsx
  src/components/Applicant/Applicant.scss
  src/components/Applicant/Applicant.tsx
  src/components/ApplicantForm/ApplicantForm.tsx
  src/components/Header/Header.scss
  src/components/Inbox/Inbox.tsx
  src/components/MessageForm/MessageForm.scss
  src/components/MessageForm/MessageForm.tsx
  src/components/SearchResults/SearchResults.tsx
  src/contexts/index.tsx
Labels: Applicant, FE, enhancement, post

#56 Testing/eu render tests
  package-lock.json
  package.json
  src/components/App/App.test.tsx
  src/components/App/App.tsx
  src/components/Header/Header.scss
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Home/Home.test.tsx
  src/components/Search/Search.test.tsx
  src/components/Search/Search.tsx
  src/components/SearchResults/SearchResults.tsx
Labels: Check In 4

#58 Testing/ak #50
  src/components/Applicant/Applicant.test.tsx
  src/components/Applicant/Applicant.tsx
  src/components/ApplicantForm/ApplicantForm.test.tsx
  src/components/ApplicantPreview/ApplicantPreview.test.tsx
  src/components/Inbox/Inbox.test.tsx
  src/components/Inbox/Inbox.tsx
  src/components/MessageForm/MessageForm.test.tsx
  src/components/MessageForm/MessageForm.tsx
  src/components/SearchResults/SearchResults.test.tsx
  src/components/SearchResults/SearchResults.tsx
Labels: FE, testing

#74 Style/eu home
  README.md
  src/components/App/App.tsx
  src/components/Applicant/Applicant.tsx
  src/components/ApplicantForm/ApplicantForm.tsx
  src/components/ApplicantPreview/ApplicantPreview.tsx
  src/components/Home/Home.scss
  src/components/Home/Home.tsx
  src/components/Inbox/Inbox.test.tsx
  src/components/Inbox/Inbox.tsx
  src/components/MessageForm/MessageForm.tsx
  src/components/Search/Search.tsx
  src/components/SearchResults/SearchResults.tsx
Labels: eval

#81 Clean data
  src/assets/api-calls.tsx
  src/assets/definitions.tsx
  src/assets/helpers.tsx
  src/components/Applicant/Applicant.test.tsx
  src/components/Applicant/Applicant.tsx
  src/components/ApplicantForm/ApplicantForm.test.tsx
  src/components/ApplicantForm/ApplicantForm.tsx
  src/components/Search/Search.test.tsx
  src/components/Search/Search.tsx
  src/components/SearchResults/SearchResults.test.tsx
  src/components/SearchResults/SearchResults.tsx
Labels: FE, enhancement, refactor

#82 Fix sorting bug #75
  src/components/SearchResults/SearchResults.tsx
Labels: FE, bug, search

#84 Style/ge revamp
  public/images/people.png
  src/_variables.scss
  src/components/ApplicantForm/ApplicantForm.scss
  src/components/ApplicantForm/ApplicantForm.tsx
  src/components/ApplicantPreview/ApplicantPreview.scss
  src/components/ApplicantPreview/ApplicantPreview.tsx
  src/components/Home/Home.scss
  src/components/Home/Home.tsx
  src/components/SearchResults/SearchResults.scss
  src/components/SearchResults/SearchResults.tsx
  src/index.scss
Labels: style

#85 Eu definition cleanup
  src/assets/definitions.tsx
  src/assets/helpers.tsx
  src/components/Applicant/Applicant.tsx
  src/components/ApplicantForm/ApplicantForm.tsx
  src/components/ApplicantPreview/ApplicantPreview.tsx
  src/components/Header/Header.tsx
  src/components/SearchResults/SearchResults.tsx
Labels: FE
