Repository HireUp-Turing/HireUp_frontend, pull requests merged in 2020-10, with the labels that each got.

#17 Feature/eu header home
  package-lock.json
  package.json
  public/close.svg
  public/images/clipboard.png
  public/index.html
  public/search.svg
  src/_variables.scss
  src/components/App/App.scss
  src/components/App/App.tsx
  src/components/Header/Header.scss
  src/components/Header/Header.tsx
  src/components/Home/Home.scss
  src/components/Home/Home.tsx
  src/components/Search/Search.scss
  src/components/Search/Search.test.tsx
  src/components/Search/Search.tsx
  src/index.scss
  src/index.tsx
  src/routes/home.tsx
  src/routes/index.tsx
Labels: Check In 2, FE, enhancement

#19 Feature/ge search with reducer hook
  src/_variables.scss
  src/assets/test-values-skills.tsx
  src/components/App/App.scss
  src/components/App/App.tsx
  src/components/Header/Header.scss
  src/components/Header/Header.tsx
  src/components/Home/Home.scss
  src/components/Search/Search.scss
  src/components/Search/Search.tsx
  src/index.scss
Labels: FE, enhancement, research

#25 Feature/eu search menu
  src/_variables.scss
  src/assets/test-values-skills.tsx
  src/components/App/App.tsx
  src/components/Header/Header.scss
  src/components/Header/Header.tsx
  src/components/Home/Home.scss
  src/components/Home/Home.tsx
  src/components/Search/Search.scss
  src/components/Search/Search.tsx
  src/contexts/index.tsx
  src/index.scss
Labels: Check In 3, FE, enhancement

#35 Feature/ge search results
  src/_variables.scss
  src/assets/definitions.tsx
  src/assets/fake-users.tsx
  src/components/Applicant/Applicant.tsx
  src/components/ApplicantPreview/ApplicantPreview.scss
  src/components/ApplicantPreview/ApplicantPreview.tsx
  src/components/Home/Home.scss
  src/components/Search/Search.tsx
  src/components/SearchResults/SearchResults.scss
  src/components/SearchResults/SearchResults.tsx
  src/contexts/index.tsx
  src/index.scss
  src/index.tsx
  src/routes/applicant.tsx
Labels: Applicant, FE, enhancement, search, style

#38 Feature/eu applicant fetch
  src/_variables.scss
  src/assets/api-calls.tsx
  src/assets/definitions.tsx
  src/assets/test-values-skills.tsx
  src/components/Applicant/Applicant.scss
  src/components/Applicant/Applicant.tsx
  src/components/ApplicantPreview/ApplicantPreview.scss
  src/components/ApplicantPreview/ApplicantPreview.tsx
  src/components/Header/Header.scss
  src/components/Header/Header.tsx
  src/components/Search/Search.tsx
  src/components/SearchResults/SearchResults.scss
  src/components/SearchResults/SearchResults.tsx
  src/index.scss
Labels: Check In 3

#39 Feature/homemade-search-menu
  package-lock.json
  package.json
  src/assets/definitions.tsx
  src/components/App/App.scss
  src/components/App/App.tsx
  src/components/Applicant/Applicant.scss
  src/components/Header/Header.scss
  src/components/Header/Header.tsx
  src/components/Search/Search.scss
  src/components/Search/Search.tsx
  src/contexts/index.tsx
  src/index.scss
Labels: FE, enhancement, search, style

#41 Feature/ge search bug fix
  src/assets/definitions.tsx
  src/components/App/App.tsx
  src/components/Header/Header.tsx
  src/components/Home/Home.tsx
  src/components/Search/Search.tsx
  src/components/SearchResults/SearchResults.tsx
  src/contexts/index.tsx
Labels: FE, bug, enhancement, routing, search

#46 Feature/eu applicant form
  src/assets/api-calls.tsx
  src/components/ApplicantForm/ApplicantForm.scss
  src/components/ApplicantForm/ApplicantForm.tsx
  src/components/Header/Header.tsx
  src/components/Home/Home.tsx
  src/components/Search/Search.scss
  src/components/Search/Search.tsx
  src/routes/applicant.tsx
Labels: Check In 4

#49 Applicant form #48
  public/refresh-pink.svg
  public/refresh-purple.svg
  src/_variables.scss
  src/assets/api-calls.tsx
  src/components/ApplicantForm/ApplicantForm.scss
  src/components/ApplicantForm/ApplicantForm.tsx
  src/index.scss
Labels: Applicant Form, Check In 4, FE, post

#52 Feature/eu applicant form
  public/magnifying-gray.svg
  public/magnifying-pink.svg
  src/_variables.scss
  src/assets/api-calls.tsx
  src/assets/definitions.tsx
  src/components/Applicant/Applicant.scss
  src/components/Applicant/Applicant.tsx
  src/components/ApplicantForm/ApplicantForm.scss
  src/components/ApplicantForm/ApplicantForm.tsx
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Home/Home.test.tsx
  src/components/Search/Search.test.tsx
  src/components/Search/Search.tsx
  src/index.scss
Labels: Check In 4
